<?php

define('VIEW', '..'.DIRECTORY_SEPARATOR.'templates'.DIRECTORY_SEPARATOR);
define('IMS', 'images'.DIRECTORY_SEPARATOR);
define('CONTROLLER', '..'.DIRECTORY_SEPARATOR.'engine'.DIRECTORY_SEPARATOR.'controller.php');
define('AUTORIZATION', '..'.DIRECTORY_SEPARATOR.'engine'.DIRECTORY_SEPARATOR.'autorization.php');
define('MODULES', '..'.DIRECTORY_SEPARATOR.'engine'.DIRECTORY_SEPARATOR.'modules'.DIRECTORY_SEPARATOR);
define('BD', '..'.DIRECTORY_SEPARATOR.'data'.DIRECTORY_SEPARATOR.'BD.php');